website/models.py
from . import db
from flask_login import UserMixin


"""Defines Database User objects"""
class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(150), unique = True)
    password = db.Column(db.String(150))
    name = db.Column(db.String(150))
    age = db.Column(db.INT())

website/__init__.py
from flask import Flask
from flask import current_app
from flask_sqlalchemy import SQLAlchemy
from os import path

db = SQLAlchemy()
DB_NAME = "database.db"


def create_app():
    app = Flask(__name__)
    app.config['SECRET_KEY'] = "NoroxCarl"
    app.config['SQLALCHEMY_DATABASE_URI'] = f'sqlite:///{DB_NAME}'
    db.init_app(app)

    from .views import views
    from .auth import auth

    app.register_blueprint(views, url_prefix="/")
    app.register_blueprint(auth, url_prefix="/")

    from .models import User
    with app.app_context():
        db.create_all()

    return app

def create_database(app):
    with current_app.app_context():
        if not path.exists('website/' + DB_NAME):
            db.create_all(app=app)
            print('Created Database!')

website/auth.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from jinja2 import Environment, FileSystemLoader
from .models import User
from werkzeug.security import generate_password_hash, check_password_hash #library to hash passwords
from . import db

auth = Blueprint('auth', __name__)

@auth.route('/login', methods=['GET','POST'])
def login():
     if request.method == 'POST':
         email =request.form.get('email')
         password =request.form.get('password')

         user = User.query.filter_by(email=email).first()
         if user:
             if check_password_hash(user.password, password):
                 flash('Logged in successfully!', category='success')
                 return redirect(url_for('views.subject'))
             else:
                 flash("Incorrect Password, try again", category='error')
         else:
             flash('Email does not Exist')
                
     
     return render_template("login.html", boolean=True)


@auth.route('/logout')
def logout():
    return "<p>logout</p>"

@auth.route('/sign-up',  methods=['GET','POST'])
def sign_up():
    if request.method == 'POST':
        email = request.form.get('email')
        name = request.form.get('name')
        password = request.form.get('password')
        confirmpassword = request.form.get('confirmpassword')
        age = request.form.get('age')
        print("success:", email)

        #Error handling, Dont forget to implement the flashes later
        user = User.query.filter_by(email=email).first()
        if user:
            flash("Email already exists", category="error")
        elif not email or len(email) < 4:
            flash("Invalid Email", category="error")
        elif not name or len(name) < 2:
            flash("Invalid name", category="error")
        elif not password or len(password) < 4:
            flash("Password is too short", category="error")
        elif password != confirmpassword:
            flash("Passwords do not match", category="error")
        elif not age or len(age) < 1:
            flash("Please enter age", category="error")
        else:
            new_user = User(email=email, name=name, age=age, password=generate_password_hash(password, method='sha256'))
            db.session.add(new_user)
            db.session.commit()
            flash(" Account created!", category="success")
            return redirect(url_for('auth.login'))
        
    return render_template("index.html")

website/views.py
from flask import Blueprint, render_template
from jinja2 import Environment, FileSystemLoader
from .fetch_youtube import fetch_youtube_data

views = Blueprint('views', __name__)

@views.route('/')
def landing():
    return render_template("landing.html")

@views.route('/home')
def home():
    return render_template("home.html")

@views.route('/subject')
def subject():
    return render_template("subject.html")

@views.route('/math')
def math():
    math_youtube_data = fetch_youtube_data("Mathematics")
    return render_template('math.html', subject='Math', youtube=math_youtube_data)


@views.route('/science')
def science():
    science_youtube_data = fetch_youtube_data("Science")
    return render_template('science.html', subject='Science', youtube=science_youtube_data)


@views.route('/history')
def history():
    history_youtube_data = fetch_youtube_data("History")
    return render_template('history.html', subject='History', youtube=history_youtube_data)

website/templates/history.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    <div class="header"><h1 class="heading">videos for {{ subject }}</h1></div>

    <div class="video-list">
      {% for video in youtube %}
      <div class="video">
        <center>
          <img src="{{ video.image_link }}" alt="{{ video.title }}" />
        </center>
        <center><h2>{{ video.title }}</h2></center>
        <center><p>Author: {{ video.author }}</p></center>
        <center>
          <a href="{{ video.video_link }}" target="_blank">Watch Online</a>
        </center>
      </div>
      {% endfor %}
    </div>
    <style>
      * {
        padding: 0;
        margin: 0;
        font-family: Arial, Helvetica, sans-serif;
      }
      .screen {
        height: 100vh;
        width: 100vw;
      }
      .header {
        display: flex;
        justify-content: center;
        align-items: center;
        background-color: #1b6b93;
        height: 20vh;
        margin-bottom: 2vh;
      }
      .heading {
        color: white;
      }
      .video {
        padding: 2%;
      }
      .video-list {
        display: flex;
      }
    </style>
  </body>
</html>

website/templates/home.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Welcome</title>
  </head>
  <body>
    <div class="screen">
      <div class="child"><p><h1 class="welcome">Welcome</h1></p>

    </div>
    </div>
  </body>
  <style>
    * {
      padding: 0;
      margin: 0;
      font-family: Arial, Helvetica, sans-serif;
    }
    .screen {
      height: 100vh;
      width: 100vw;
      background-color: #a2ff86;
      display: flex;
      justify-content: center;
      align-items: center;
    }
    .welcome {
      color: #164b60;
    }
    h1 {
        text-align: center;
    }
    
  </style>
</html>

website/templates/index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Signup or Login</title>
  </head>
  <body>
    <div class="screen">
      <div class="header">
        <div class="child"><h1 class="sitename">Edulink</h1></div>
      </div>
      <div class="slogan">
        <div class="child">
          <h2 class="quote">Empowering Minds, Changing Lives</h2>
        </div>
      </div>
      <div class="block">
        <form class="form" method="POST">
          <div class="container">
            <h2 class="signup">Sign up</h2>
            {% with messages = get_flashed_messages(with_categories=true) %} {%
            if messages %} {% for message in messages %}
            <div class="message" role="alert">
              <center>{{ message }}</center>
            </div>
            {% endfor %} {% endif %} {% endwith %}

            <div class="inputholder">
              <input
                type="text"
                class="input"
                placeholder="Enter Fullname"
                id="name"
                name="name"
              />
            </div>
            <div class="inputholder">
              <input
                type="email"
                class="input"
                placeholder="Enter email"
                id="email"
                name="email"
              />
            </div>
            <div class="inputholder">
              <input
                type="password"
                class="input"
                placeholder="Enter password"
                id="password"
                name="password"
              />
            </div>
            <div class="inputholder">
              <input
                type="password"
                class="input"
                placeholder="Confirm password"
                id="confirmpassword"
                name="confirmpassword"
              />
            </div>
            <div class="inputholder">
              <input
                type="text"
                class="input"
                placeholder="Enter age"
                id="age"
                name="age"
              />
            </div>
            <div class="inputholder">
              <button type="submit"><b>Done</b></button>
            </div>
            <div class="loginholder">
              <span class="text"
                >Already have an account?
                <a href="{{ url_for('auth.login') }}" class="login"
                  >login</a
                ></span
              >
            </div>
          </div>
        </form>
      </div>
    </div>
  </body>
  <style>
    * {
      padding: 0;
      margin: 0;
      font-family: Arial, Helvetica, sans-serif;
    }
    .screen {
      height: 100vh;
      width: 100vw;
    }
    .header {
      display: flex;
      justify-content: center;
      align-items: center;
      background-color: #1b6b93;
      height: 20vh;
    }
    .sitename {
      color: white;
    }
    .slogan {
      display: flex;
      justify-content: center;
      align-items: center;
      background-color: #4fc0d0;
      height: 10vh;
    }
    .quote {
      color: white;
    }
    .block {
      width: 100vw;
      height: 70vh;
      display: flex;
      justify-content: center;
      align-items: center;
    }
    .form {
      background-color: #a2ff86;
      width: 40vw;
      height: 70vh;
      display: flex;
      justify-content: center;
      align-items: center;
    }
    .inputholder {
      height: 5vh;
      width: 15vw;
      margin: 2vh;
      padding: 5%;
    }
    .signup {
      text-align: center;
      color: #164b60;
    }
    .input {
      height: 100%;
      width: 100%;
      border-color: transparent;
    }
    .text {
      color: #164b60;
    }
    button {
      width: 100%;
      height: 5vh;
      color: white;
      background-color: #164b60;
      border-radius: 10cm;
    }
  </style>
</html>

website/templates/landing.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Welcome</title>
  </head>
  <body>
    <div class="screen">
      <div class="child"><p><h1 class="welcome">Welcome to Edulink</h1></p>
        <p><h1 class="welcome">Where we connect minds through education</h1></p>
        <center><a href="{{ url_for('auth.sign_up') }}"><button class="button">Let's Get Started!</button></a></center>
    </div>
    </div>
  </body>
  <style>
    * {
      padding: 0;
      margin: 0;
      font-family: Arial, Helvetica, sans-serif;
    }
    .screen {
      height: 100vh;
      width: 100vw;
      background-color: #a2ff86;
      display: flex;
      justify-content: center;
      align-items: center;
    }
    .welcome {
      color: #164b60;
    }
    h1 {
        text-align: center;
    }
    .button {
        background-color: #164b60;
        color: white;
        width: 10vw;
        height: 5vw;
        border-radius: 20cm
    }
    a{
        text-decoration: none;
    }
  </style>
</html>

website/templates/login.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>landing page</title>
  </head>
  <body>
    <div class="screen">
      <div class="header">
        <div class="child"><h1 class="sitename">Edulink</h1></div>
      </div>
      <div class="slogan">
        <div class="child">
          <h2 class="quote">Welcome back !</h2>
        </div>
      </div>
      <div class="block">
        <form class="form" method="POST">
          <div class="container">
            <h2 class="signup">Log in</h2>
            <div class="inputholder">
              <input type="text" class="input" placeholder="Enter email" id="email" name="email"/>
            </div>
            <div class="inputholder">
              <input type="password" class="input" placeholder="Enter password" id="password" name="password"/>
            </div>
            <div class="inputholder">
              <button><b>Login</b></button>
            </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </body>
  <style>
    * {
      padding: 0;
      margin: 0;
      font-family: Arial, Helvetica, sans-serif;
    }
    .screen {
      height: 100vh;
      width: 100vw;
    }
    .header {
      display: flex;
      justify-content: center;
      align-items: center;
      background-color: #1b6b93;
      height: 20vh;
    }
    .sitename {
      color: white;
    }
    .slogan {
      display: flex;
      justify-content: center;
      align-items: center;
      background-color: #4fc0d0;
      height: 10vh;
    }
    .quote {
      color: white;
    }
    .block {
      width: 100vw;
      height: 70vh;
      display: flex;
      justify-content: center;
      align-items: center;
    }
    .form {
      background-color: #a2ff86;
      width: 40vw;
      height: 60vh;
      display: flex;
      justify-content: center;
      align-items: center;
    }
    .inputholder {
      height: 5vh;
      width: 15vw;
      margin: 2vh;
      padding: 5%;
    }
    .signup {
      text-align: center;
      color: #164b60;
    }
    .input {
      height: 100%;
      width: 100%;
      border-color: transparent;
    }
    .text {
      color: #164b60;
    }
    button {
      width: 100%;
      height: 5vh;
      color: white;
      background-color: #164b60;
      border-radius: 10cm;
    }
  </style>
</html>

website/templates/math.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    <div class="header"><h1 class="heading">videos for {{ subject }}</h1></div>

    <div class="video-list">
      {% for video in youtube %}
      <div class="video">
        <center>
          <img src="{{ video.image_link }}" alt="{{ video.title }}" />
        </center>
        <center><h2>{{ video.title }}</h2></center>
        <center><p>Author: {{ video.author }}</p></center>
        <center>
          <a href="{{ video.video_link }}" target="_blank">Watch Online</a>
        </center>
      </div>
      {% endfor %}
    </div>
    <style>
      * {
        padding: 0;
        margin: 0;
        font-family: Arial, Helvetica, sans-serif;
      }
      .screen {
        height: 100vh;
        width: 100vw;
      }
      .header {
        display: flex;
        justify-content: center;
        align-items: center;
        background-color: #1b6b93;
        height: 20vh;
        margin-bottom: 2vh;
      }
      .heading {
        color: white;
      }
      .video {
        padding: 2%;
      }
      .video-list {
        display: flex;
      }
    </style>
  </body>
</html>

website/templates/science.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    <div class="header"><h1 class="heading">videos for {{ subject }}</h1></div>

    <div class="video-list">
      {% for video in youtube %}
      <div class="video">
        <center>
          <img src="{{ video.image_link }}" alt="{{ video.title }}" />
        </center>
        <center><h2>{{ video.title }}</h2></center>
        <center><p>Author: {{ video.author }}</p></center>
        <center>
          <a href="{{ video.video_link }}" target="_blank">Watch Online</a>
        </center>
      </div>
      {% endfor %}
    </div>
    <style>
      * {
        padding: 0;
        margin: 0;
        font-family: Arial, Helvetica, sans-serif;
      }
      .screen {
        height: 100vh;
        width: 100vw;
      }
      .header {
        display: flex;
        justify-content: center;
        align-items: center;
        background-color: #1b6b93;
        height: 20vh;
        margin-bottom: 2vh;
      }
      .heading {
        color: white;
      }
      .video {
        padding: 2%;
      }
      .video-list {
        display: flex;
      }
    </style>
  </body>
</html>

website/templates/subject.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Available Subjects </title>
  </head>
  <body>
    <div class="screen">
      <div class="header">
        <div class="child"><h1 class="sitename">Welcome pick a subject</h1></div>
      </div>
      <form action="POST" class="form">
        <div class="subjectholder">
          <div class="subject"><h1><a href="{{ url_for('views.math') }}">Math</a></h1></div>
        </div>
        <div class="subjectholder">
          <div class="subject"><h1><a href="{{ url_for('views.science') }}">Science</h1></div>
        </div>
        <div class="subjectholder">
          <div class="subject"><h1><a href= "{{ url_for('views.history') }}">History</h1></div>
        </div>
      </form>
      

    </div>
    </div>
  </body>
  <style>
    * {
      padding: 0;
      margin: 0;
      font-family: Arial, Helvetica, sans-serif;
    }
    .screen {
      height: 100vh;
      width: 100vw;
      background-color: #a2ff86;
    }
    .header{
      background-color: #1b6b93;
      display: flex;
      justify-content: center;
      align-items: center;
      height:20vh;
      width: 100vw;
    }
    h1 {
      color: white;
    }

    .subjectholder {
      background-color: #4fc0d0;
      height: 50vh;
      width: 30vw;
      margin: 5%;
      display: flex;
      justify-content: center;
      align-items: center;
      
    }
    .subjectholder:hover {
      height : 55vh;
      width: 30vw;
    }
    .form{
      display: flex;
      justify-content: space-between;
    }

      
   

   
    
    
  </style>
</html>